# Limiter configuration for SearXNG
# This configuration allows JSON API access from AnythingLLM

[botdetection.ip_limit]
# Disable strict bot detection to allow JSON API access
filter_link_local = false
link_token = false

[botdetection.ip_lists]
# Allow local network access (Docker containers)
pass_ip = [
    '127.0.0.1',
    '::1',
    '172.16.0.0/12',  # Docker default networks
    '10.0.0.0/8',     # Private networks
    '192.168.0.0/16'  # Private networks
]

block_ip = []
