# SearXNG configuration for AnythingLLM integration
# This configuration enables JSON API access for programmatic use
use_default_settings: true

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "change-this-secret-key-for-production"
  base_url: false
  image_proxy: true
  # Allow JSON API access
  public_instance: false

search:
  # Enable JSON format for API access
  formats:
    - html
    - json
    - csv
    - rss
  safe_search: 0
  autocomplete: ""
  default_lang: ""
  # Disable request timeout for better reliability
  request_timeout: 10.0

ui:
  static_use_hash: false
  default_theme: simple
  center_alignment: false
  results_on_new_tab: false
  advanced_search: true
  query_in_title: false

# Disable bot detection for JSON API access
enabled_plugins: []

# Enable basic engines
engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: startpage
    engine: startpage
    shortcut: sp
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false